import React, { StrictMode, useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { analyzeImage, getHistory, login, logout, refresh, register } from './services/api/api.js';
import './styles.css';

const MAX_BYTES = 8 * 1024 * 1024;
const TYPES = ['image/jpeg', 'image/png', 'image/webp'];

function validateFile(file) {
  if (!file) return 'Choose an image first.';
  if (!TYPES.includes(file.type)) return 'Use a JPEG, PNG, or WebP image.';
  if (file.size > MAX_BYTES) return 'Images must be smaller than 8 MB.';
  return '';
}

function AuthPanel({ onAuth, onClose }) {
  const [mode, setMode] = useState('login'); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function submit(event) { event.preventDefault(); setBusy(true); setError(''); try { const result = mode === 'login' ? await login(email, password) : await register(email, password); onAuth(result.user); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <div className="modal-backdrop"><form className="auth-card" onSubmit={submit}><button type="button" className="close" onClick={onClose}>×</button><p className="eyebrow">YOUR PRIVATE SPACE</p><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p className="muted">Save assessment metadata to your private history. Images are never saved.</p><label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} required autoComplete="email" /></label><label>Password<input type="password" minLength="8" value={password} onChange={(e) => setPassword(e.target.value)} required autoComplete={mode === 'login' ? 'current-password' : 'new-password'} /></label>{error && <div className="alert error">{error}</div>}<button className="primary" disabled={busy}>{busy ? 'Working…' : mode === 'login' ? 'Log in' : 'Create account'}</button><button type="button" className="link-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Create one' : 'Already have an account? Log in'}</button></form></div>;
}

function UploadCard({ onResult, loggedIn }) {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [consent, setConsent] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const inputRef = useRef(null);
  function choose(next) { const problem = validateFile(next); setError(problem); if (problem) return; setFile(next); setPreview(URL.createObjectURL(next)); }
  function onDrop(event) { event.preventDefault(); choose(event.dataTransfer.files?.[0]); }
  async function submit() { if (!consent) return setError('Please confirm that you consent to sending the photo to the third-party AI provider.'); setBusy(true); setError(''); try { onResult(await analyzeImage(file)); } catch (err) { setError(err.message); } finally { setBusy(false); } }
  return <section className="upload-card" onDragOver={(e) => e.preventDefault()} onDrop={onDrop}><div className="card-heading"><div><p className="eyebrow">01 / PHOTO CHECK</p><h2>See what your skin may be showing</h2></div><span className="status-dot">PRIVATE BY DEFAULT</span></div><div className={`dropzone ${preview ? 'has-preview' : ''}`} onClick={() => inputRef.current?.click()}>{preview ? <img src={preview} alt="Selected skin photo preview" /> : <><div className="upload-icon">＋</div><strong>Drop a clear face photo here</strong><span>or click to browse · JPEG, PNG, WebP · max 8 MB</span><span className="camera-note">Mobile camera is supported</span></>}<input ref={inputRef} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="user" onChange={(e) => choose(e.target.files?.[0])} /></div>{file && <div className="file-row"><span>{file.name}</span><button className="link-button" onClick={() => { setFile(null); setPreview(''); }}>Remove</button></div>}<label className="consent"><input type="checkbox" checked={consent} onChange={(e) => setConsent(e.target.checked)} /> <span>I understand this photo is sent to a third-party AI provider for analysis and is not stored by Classification of Acne.</span></label>{error && <div className="alert error">{error}</div>}<button className="primary wide" disabled={!file || busy} onClick={submit}>{busy ? <><span className="spinner" /> Analyzing carefully…</> : 'Analyze my photo →'}</button>{loggedIn && <p className="helper">Your result will be saved as metadata to your private history. The image is discarded after processing.</p>}</section>;
}

function ResultCard({ result, onReset }) { const severe = result.severity === 'severe'; return <section className="result-card"><div className="result-top"><div><p className="eyebrow">ASSESSMENT COMPLETE</p><h2>Your estimated profile</h2></div><div className={`confidence ${severe ? 'danger' : ''}`}>{Math.round(result.confidence * 100)}%<small>confidence</small></div></div><div className="label-grid"><div><span>Severity</span><strong className={severe ? 'danger-text' : ''}>{result.severity}</strong></div><div><span>Lesion pattern</span><strong>{result.lesionType}</strong></div></div><div className="reason"><span>Why this estimate</span><p>{result.reason}</p></div><div className="tips"><span>Gentle next steps</span><ul>{result.tips?.map((tip) => <li key={tip}>{tip}</li>)}</ul></div>{severe && <div className="alert severe">This result suggests you should arrange professional dermatology care, especially if lesions are painful, spreading, or scarring.</div>}<p className="disclaimer">AI estimate, not a medical diagnosis. See a dermatologist for medical advice.</p><button className="secondary" onClick={onReset}>Analyze another photo</button></section>; }

function History({ items }) { return <section className="history-card"><p className="eyebrow">YOUR HISTORY</p><h2>Recent estimates</h2>{items.length === 0 ? <p className="muted">No saved assessments yet.</p> : <div className="history-list">{items.map((item) => <div className="history-item" key={item._id}><div><strong>{item.severity}</strong><span>{item.lesionType}</span></div><time>{new Date(item.createdAt).toLocaleDateString()}</time></div>)}</div>}<p className="disclaimer">AI estimate, not a medical diagnosis. See a dermatologist for medical advice.</p></section>; }

function App() {
  const [result, setResult] = useState(null); const [user, setUser] = useState(null); const [history, setHistory] = useState([]); const [showAuth, setShowAuth] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('clearskin-theme') === 'dark'); const [globalError, setGlobalError] = useState('');
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('clearskin-theme', dark ? 'dark' : 'light'); }, [dark]);
  async function handleAuth(nextUser) { setUser(nextUser); setShowAuth(false); try { setHistory((await getHistory()).items); } catch (err) { setGlobalError(err.message); } }
  async function handleLogout() { await logout().catch(() => {}); setUser(null); setHistory([]); }
  async function loadHistory() { try { setHistory((await getHistory()).items); } catch (err) { if (!String(err.message).includes('log in')) setGlobalError(err.message); } }
  useEffect(() => { refresh().then(loadHistory).catch(() => {}); }, []);
  return <div className="app-shell"><header><a className="brand" href="/" onClick={(e) => { e.preventDefault(); setResult(null); }}><span className="brand-mark">✦</span><span>Classification <em>of Acne</em></span></a><nav><button className="theme-toggle" onClick={() => setDark(!dark)}>{dark ? '☼ Light' : '◐ Dark'}</button>{user ? <><button className="nav-button" onClick={loadHistory}>History</button><button className="nav-button" onClick={handleLogout}>Log out</button></> : <button className="nav-button" onClick={() => setShowAuth(true)}>Log in</button>}</nav></header><main><div className="hero"><div><p className="eyebrow">A CALMER WAY TO LOOK CLOSER</p><h1>Understand your skin.<br /><span>Without the guesswork.</span></h1><p className="hero-copy">Upload a clear face photo for a gentle, AI-estimated acne assessment. Built to inform your next step—not replace a professional.</p></div><div className="hero-note"><span>✦</span><p>Thoughtful AI, transparent limits.<br /><strong>Your photo is processed in memory.</strong></p></div></div>{globalError && <div className="alert error">{globalError}</div>}{result ? <ResultCard result={result} onReset={() => setResult(null)} /> : <UploadCard onResult={setResult} loggedIn={Boolean(user)} />}{user && <History items={history} />}</main><footer><span>Classification of Acne / student project</span><span>Not medical advice · Your privacy matters</span></footer>{showAuth && <AuthPanel onAuth={handleAuth} onClose={() => setShowAuth(false)} />}</div>;
}

createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
